// http://www.irchelp.org/irchelp/ircii/server-numerics.txt
// ref. http://www.mirc.net/raws/
'use strict';

var IRC;
if (typeof IRC === 'undefined') IRC = {};

IRC.Errors = {
  NOSUCHNICK: '401',
  NOSUCHSERVER: '402',
  NOSUCHCHANNEL: '403',
  CANNOTSENDTOCHAN: '404',
  TOOMANYCHANNELS: '405',
  WASNOSUCHNICK: '406',
  TOOMANYTARGETS: '407',
  NOSUCHSERVICE: '408',
  NORECIPIENT: '411',
  NOTEXTTOSEND: '412',
  NOTOPLEVEL: '413',
  WILDTOPLEVEL: '414',
  UNKNOWNCOMMAND: '421',
  NONICKNAMEGIVEN: '431',
  ERRONEUSNICKNAME: '432',
  NICKNAMEINUSE: '433',
  SERVICENAMEINUSE: '434',
  SERVICECONFUSED: '435',
  USERNOTINCHANNEL: '441',
  NOTONCHANNEL: '442',
  USERONCHANNEL: '443',
  NOTREGISTERED: '451',
  NEEDMOREPARAMS: '461',
  ALREADYREGISTRED: '462',
  NOPERMFORHOST: '463',
  PASSWDMISMATCH: '464',
  YOUREBANNEDCREEP: '465',
  YOUWILLBEBANNED: '466',
  CHANNELISFULL: '471',
  UNKNOWNMODE: '472',
  INVITEONLYCHAN: '473',
  BANNEDFROMCHAN: '474',
  NOPRIVILEGES: '481',
  CHANOPRIVSNEEDED: '482',
  NOOPERHOST: '491',
  NOSERVICEHOST: '492',
  UMODEUNKNOWNFLAG: '501',
  USERSDONTMATCH: '502'
};

IRC.isError = function(command) {
  return command.match(/^4\d{2}$/);
};
